name: Build gallery

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Restore data cache
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ~/.cache/topotoolbox
          key: tt3-gallery-data
      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Install Python build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.workspace }}/requirements.txt
      - name: Ensure API key is available for examples that require it
        env:
          OPENTOPOGRAPHY_API_KEY: ${{ secrets.OPENTOPOGRAPHY_API_KEY }}
        run: |
          printf '%s' "$OPENTOPOGRAPHY_API_KEY" > $HOME/.opentopography.txt
          mkdir -p $HOME/.matlab/R2025b
          cp $HOME/.opentopography.txt $HOME/.matlab/R2025b/opentopography.apikey
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2025b
          cache: true
          products: |
            Mapping_Toolbox
            Image_Processing_Toolbox
            Optimization_Toolbox
      - name: Run MATLAB build
        uses: matlab-actions/run-build@v2
      - name: Build sphinx documentation
        run: |
          make clean
          make html
      - name: Package artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.workspace }}/build/html
  deploy:
    if: ${{ github.repository_owner == 'TopoToolbox' }}
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
